### ISSUE TITLE
Bug: 'Enter password to decrypt files' not working

### ISSUE THREAD

**Issue by kikkoi** [kjk/edna#15]
**Describe the bug**

I tried using the password to encrypt the files, and it worked well. However, when I tried to decrypt the files with the same password, it gave an error saying, 'Password must be at least 8 characters long.' In the console, it shows 'Error: invalid tag.'

**Expected behavior**
I expected to decrypt the files

**Screenshots**

![image](https://github.com/kjk/edna/assets/12332801/4aa7f94f-6a73-47d2-ac33-2b3bc5b81006)

**Desktop (please complete the following information):**
Windows 10, Chrome 126.0.6478.127

**Comment by kjk** [comment]
Well, the wording here is confusing but here's what happened:
* you entered incorrect password
* we failed to decrypt (`Error: invalid tag` from encryption library)
* which is why we show this dialog so that you can enter the correct password
* notice the error in red says `Entered password was invalid`
* the error about empty password is just additional validation

I should re-word this dialog to be more clear about the fact you entered invalid password and have to enter a new one.

Also, how did you get in that state? Did you delete the local storage key that stored the password?

**Comment by kjk** [comment]
I tweaked the message and re-testes decryption logic and it works for me.
