### ISSUE TITLE
Saving to GitHub Gists

### ISSUE THREAD

**Issue by semanticdata** [kjk/edna#2]
**Have you searched existing GitHub issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
Please provide more info on how to log in with GitHub and store as encrypted Gist.

**Describe the solution you'd like**
A quick tutorial on how to use the feature.

**Describe alternatives you've considered**
I tied looking around but didn't find mention of this except in the README.

https://github.com/kjk/edna/blob/a908ce3df435e6bdc6443117faaedd9def756e46/README.md?plain=1#L123

**Comment by kjk** [comment]
Sorry, outdated info, I've updated the readme.

I wrote [Gist Editor](https://tools.arslexis.io/gisteditor/) so I have experience with that and my initial plan was to use gist as a backend for storing files. Hence the info in readme.

However, I decided against it because GitHub API is slow, especially with lots of gists.

Storing files on disk (https://edna.arslexis.io/help#storing-notes-on-disk) was much easier to implement and provides better experience (speed) for the user.

For sharing between computers you can store notes on DropBox/OneDrive/Google Drive etc. folder.

**Comment by semanticdata** [comment]
Not a problem. Thanks for the quick reply.
