### ISSUE TITLE
Bug: Rendering of different syntax highlighted blocks in longer note files un stable

### ISSUE THREAD

**Issue by Wesleychiyoka** [kjk/edna#22]
**Describe the bug**
At longer note sizes, a few code snippets in one file the rendering begins to lag and cause the cursor to jump around, as well as expose the underlying markings e.g.  '∞∞∞markdown' end up being seen on screen just displaying the underlying text file

**To Reproduce**
1. Work on a Longer note file with multiple blocks ~ >3500 lines
2. operate and write inserting new blocks and moving text as normal
3. experience UI slow down and rendering failures
4.Aditionally mark down rendering of tick boxes takes a hit 
    
![image](https://github.com/kjk/edna/assets/100045903/f71820fa-ed54-4487-968c-f3251c155ba9)

**Expected behavior**
smooth UI and text processing without instability when editing separate note buffers
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Arc Browser, Microsoft Edge tested 
 - Version [e.g. 1.6.0-beta]

**Additional context**
I may be pushing what note limits should be but I've jumped on the tool for its amazing speed and block centred approach with different notes

**Comment by kjk** [comment]
I can repro this in this specific scenario:
* create a large block
* create a small block
* create a large block

Then do `Del` in small black.

That causes the flashing.

According to profile this is caused by `deleteByChar` eventually triggering `getBlocks` which call's codemirror's `advance`, `advanceStack`, `addActions`.

This only happens on delete so it's possible it can be optimized.

**Comment by kjk** [comment]
The problem is that in `getBlocks()`, when we have text deletion or replacement, `ensureSyntaxTree` returns no tree 3 times, until it finally returns a tree.

Those invocations take time during which the document shows unstyled.

It doesn't happen on adding text.

Should figure out why it `ensureSyntaxTree` has to be called 4 times on deletion.

Also, a more difficult but possible would be to re-calculate block state from existing state and transaction. Tricky logic to re-calculate positions but should be doable.

**Comment by kjk** [comment]
The issue is that `ensureSyntaxTree` runs so much longer when there is deletion vs. just insertion that it exceeds timeout, which leaves the doc in unstyled state until it finishes.

It's CodeMirror's code so no idea why it takes so long.

Need to profile both version to see why they differ so much in time.

**Comment by kjk** [comment]
All the time is spent inside CodeMirror so I have no idea what's going on. I think it's running syntax for the whole document, which will be slow. I think CodeMirror is fast because it only runs this on the visible part of the document, but `getBlocks()` runs it on whole document to figure out blocks boundary.

New idea: re-implement `getBlocks()` to just look for block boundaries without syntax parsing, just `indexOf("\n∞∞∞")`

**Comment by kjk** [comment]
Rewrote `getBlocks()` to be drastically faster. On my test 350kb document: 250ms => 2ms.

No more showing underlying markings when deleting text.
