### ISSUE TITLE
Bug: switch to local storage didn't create files

### ISSUE THREAD

**Issue by jots** [kjk/edna#29]
**Describe the bug**
I switched to local storage but it did't create the files and content of the buffers were lost.
if I create a new buffer, the file.edna.txt is created in the directory.

also now alt-2 does not bring up daily journal, alt-1 doesn't bring up scratch.

if I switch back to browser storage the alt-$x keys work again.
**Desktop (please complete the following information):**
 - OS: Linux
 -  Chrome Version 125.0.6422.76

**Comment by nosas** [comment]
For those affected by this issue, how can we restore the journal's automatic daily block generation?

**Comment by kjk** [comment]
Several issues here.

I know it's potentially confusing but there is not "disk => local storage" move. The doc https://edna.arslexis.io/help-win#storing-notes-on-disk say: `Unlike going from browser => directory, it doesn't import the notes from directory`.

In my mind local storage is if the browser doesn't support disk or for trying out.

Storing on disk is for real work.

That's why the menu item is `Move notes from browser to directory` and others are `Switch to notes ...`.

You can think of switching like having multiple workspaces with notes and switching between them.

So I didn't implement moving from disk back to local storage. I could but I would need a good reason for that.

That being said, there were a few bugs that I fixed.

I temporarily fixed `create with Enter` in note selector dialog, which is what you probably saw.

Loosing quick access keys was a side effect of not moving metadata file, which I fixed.

So going forward those issues should be fixed.

But maybe I missed some scenarios so if you see new bugs please open an issue with step-by-step repro scenario.

**Comment by kjk** [comment]
@nosas Yes, some note names (`scratch`, `daily journal`) have special meaning. Auto-creation of daily entries only applies in `daily journal` note although I have an idea on how enable it for any note https://github.com/kjk/edna/issues/25
